extends  Node

signal player_entered_kill_zone
signal player_colliding_y
signal player_colliding_x
signal player_enter_room
signal player_exit_room
signal player_get_momentum
signal save_game
signal player_refill_dash
